version: "3"

services:
  drand-nginx:
    container_name: drand-nginx
    image: drandorg/go-drand:v1.5.3-testnet
    command: start --verbose --tls-disable --private-listen 0.0.0.0:8080 --control 8888 --public-listen 0.0.0.0:9080
    volumes:
      - drand-nginx:/data/drand
    restart: always
    ports:
      - 8080:8080
      - 8888:8888
      - 9080:9080
  nginx:
    container_name: nginx
    image: nginx:1.23.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 81:81
      - 443:443
    links:
      - drand-nginx

volumes:
  drand-nginx:
    external: true
    name: drand-nginx

