name: Label syncer
on:
  push:
    paths:
      - '.github/labels.yml'
    branches:
      - master
jobs:
  sync_labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3.3.0
      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
